GRDIR = S:\gr
QTDIR = S:\Qt\5.7.0
CXXFLAGS = /I$(QTDIR)\include /I$(QTDIR)\include\QtCore /I$(QTDIR)\include\QtGui /I$(QTDIR)\include\QtWidgets /I$(GRDIR) /Zi
LIBS = /LIBPATH:$(QTDIR)\lib /LIBPATH:$(GRDIR) Qt5Widgets.lib Qt5Gui.lib Qt5Core.lib libgr.lib qt5gr.lib
OBJ = main.obj main_window.obj


all: main.exe

main.exe: $(OBJ)
	$(CXX) /Fe$@ $(OBJ) /link $(LIBS)

.cpp.obj:
	$(CXX) /c $(CXXFLAGS) $<

clean:
	del main.exe *.obj *.ilk *.pdb
