<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
           vc:minVersion="1.1">

    <!-- definition of root -->
    <xs:element name="root">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="figure" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <!-- definition of figure -->
    <xs:element name="figure">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="draw_graphics" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="layout_grid" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="overlay" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="plot" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attribute name="active" type="xs:integer"/>
            <xs:attribute name="consecutive_colorbars" type="xs:integer"/>
            <xs:attribute name="size_x" type="xs:double"/>
            <xs:attribute name="size_x_type" type="xs:string"/>
            <xs:attribute name="size_x_unit" type="xs:string"/>
            <xs:attribute name="size_y" type="xs:double"/>
            <xs:attribute name="size_y_type" type="xs:string"/>
            <xs:attribute name="size_y_unit" type="xs:string"/>
            <xs:attribute name="text_encoding" type="strint"/>
            <xs:attribute name="text_scale" type="xs:double"/>
            <xs:attribute name="ws_viewport_x_max" type="xs:double"/>
            <xs:attribute name="ws_viewport_x_min" type="xs:double"/>
            <xs:attribute name="ws_viewport_y_max" type="xs:double"/>
            <xs:attribute name="ws_viewport_y_min" type="xs:double"/>
            <xs:attribute name="ws_window_x_max" type="xs:double"/>
            <xs:attribute name="ws_window_x_min" type="xs:double"/>
            <xs:attribute name="ws_window_y_max" type="xs:double"/>
            <xs:attribute name="ws_window_y_min" type="xs:double"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of layout_grid -->
    <xs:element name="layout_grid">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="layout_grid" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="layout_grid_element" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attribute name="aspect_ratio" type="xs:double"/>
            <xs:attribute name="fit_parents_height" type="xs:integer" use="required"/>
            <xs:attribute name="fit_parents_width" type="xs:integer" use="required"/>
            <xs:attribute name="flip_col_and_row" type="xs:integer"/>
            <xs:attribute name="num_col" type="xs:integer" use="required"/>
            <xs:attribute name="num_row" type="xs:integer" use="required"/>
            <xs:attribute name="start_col" type="xs:integer"/>
            <xs:attribute name="start_row" type="xs:integer"/>
            <xs:attribute name="stop_col" type="xs:integer"/>
            <xs:attribute name="stop_row" type="xs:integer"/>
            <xs:attribute name="trim_col" type="xs:integer"/>
            <xs:attribute name="trim_row" type="xs:integer"/>
            <xs:attribute name="viewport_height_abs" type="xs:double"/>
            <xs:attribute name="viewport_height_rel" type="xs:double"/>
            <xs:attribute name="viewport_normalized_x_max" type="xs:double"/>
            <xs:attribute name="viewport_normalized_x_min" type="xs:double"/>
            <xs:attribute name="viewport_normalized_y_max" type="xs:double"/>
            <xs:attribute name="viewport_normalized_y_min" type="xs:double"/>
            <xs:attribute name="viewport_width_abs" type="xs:double"/>
            <xs:attribute name="viewport_width_rel" type="xs:double"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of layout_grid_element -->
    <xs:element name="layout_grid_element">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="plot" minOccurs="0" maxOccurs="1"/>
            </xs:choice>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attribute name="aspect_ratio" type="xs:double"/>
            <xs:attribute name="col_span" type="xs:integer"/>
            <xs:attribute name="fit_parents_height" type="xs:integer" use="required"/>
            <xs:attribute name="fit_parents_width" type="xs:integer" use="required"/>
            <xs:attribute name="keep_size_if_swapped" type="xs:integer"/>
            <xs:attribute name="position" type="xs:string"/>
            <xs:attribute name="row_span" type="xs:integer"/>
            <xs:attribute name="viewport_height_abs" type="xs:double"/>
            <xs:attribute name="viewport_height_rel" type="xs:double"/>
            <xs:attribute name="viewport_normalized_x_max" type="xs:double"/>
            <xs:attribute name="viewport_normalized_x_min" type="xs:double"/>
            <xs:attribute name="viewport_normalized_y_max" type="xs:double"/>
            <xs:attribute name="viewport_normalized_y_min" type="xs:double"/>
            <xs:attribute name="viewport_width_abs" type="xs:double"/>
            <xs:attribute name="viewport_width_rel" type="xs:double"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of draw_graphics -->
    <xs:element name="draw_graphics">
        <xs:complexType>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attribute name="data" type="xs:string" use="required"/>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of overlay -->
    <xs:element name="overlay">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="overlay_element" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="move_xform_ndc"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of overlay_element -->
    <xs:element name="overlay_element">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="text" minOccurs="0" maxOccurs="unbounded"/> <!-- extend the list -->
                <xs:element ref="draw_image" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attributeGroup ref="text_modifications"/>
            <xs:attribute name="data" type="xs:string"/>
            <xs:attribute name="element_type" type="strint"/>
            <xs:attribute name="height_abs" type="xs:double"/>
            <xs:attribute name="transparency" type="xs:double"/>
            <xs:attribute name="width_abs" type="xs:double"/>
            <xs:attribute name="window_x_max" type="xs:double"/>
            <xs:attribute name="window_x_min" type="xs:double"/>
            <xs:attribute name="window_y_max" type="xs:double"/>
            <xs:attribute name="window_y_min" type="xs:double"/>
            <xs:attribute name="x" type="xs:double"/> <!-- string if more complex childs are possible -->
            <xs:attribute name="y" type="xs:double"/> <!-- string if more complex childs are possible -->
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of plot -->
    <xs:element name="plot">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="central_region" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="marginal_heatmap_plot" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="legend" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="side_region" minOccurs="0" maxOccurs="4"/>
            </xs:choice>
            <xs:attributeGroup ref="fill_modifications"/>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="text_modifications"/>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attribute name="adjust_x_lim" type="xs:integer" use="required"/>
            <xs:attribute name="adjust_y_lim" type="xs:integer" use="required"/>
            <xs:attribute name="adjust_z_lim" type="xs:integer"/>
            <xs:attribute name="background_color" type="strint"/>
            <xs:attribute name="c_lim_max" type="xs:double"/>
            <xs:attribute name="c_lim_min" type="xs:double"/>
            <xs:attribute name="char_height" type="xs:double"/>
            <xs:attribute name="color_rgb_values" type="xs:string"/>
            <xs:attribute name="colormap" type="strint"/>
            <xs:attribute name="colormap_inverted" type="xs:integer"/>
            <xs:attribute name="keep_aspect_ratio" type="xs:integer" use="required"/>
            <xs:attribute name="keep_radii_axes" type="xs:integer"/>
            <xs:attribute name="location" type="strint"/>
            <xs:attribute name="max_y_length" type="xs:integer"/>
            <xs:attribute name="only_square_aspect_ratio" type="xs:integer"/>
            <xs:attribute name="plot_group" type="xs:integer"/>
            <xs:attribute name="plot_id" type="xs:string" use="required"/>
            <xs:attribute name="polar_with_pan" type="xs:integer"/>
            <xs:attribute name="r_lim_max" type="xs:double"/>
            <xs:attribute name="r_lim_min" type="xs:double"/>
            <xs:attribute name="r_log" type="xs:integer"/>
            <xs:attribute name="reset_ranges" type="xs:integer"/>
            <xs:attribute name="scale" type="xs:integer"/>
            <xs:attribute name="theta_flip" type="xs:integer"/>
            <xs:attribute name="theta_lim_max" type="xs:double"/>
            <xs:attribute name="theta_lim_min" type="xs:double"/>
            <xs:attribute name="transparency" type="xs:double"/>
            <xs:attribute name="use_grplot_changes" type="xs:integer"/> <!-- all plots are made with grplot or none -->
            <xs:attribute name="viewport_normalized_x_max" type="xs:double"/>
            <xs:attribute name="viewport_normalized_x_min" type="xs:double"/>
            <xs:attribute name="viewport_normalized_y_max" type="xs:double"/>
            <xs:attribute name="viewport_normalized_y_min" type="xs:double"/>
            <xs:attribute name="x_flip" type="xs:integer"/>
            <xs:attribute name="x_lim_max" type="xs:double"/>
            <xs:attribute name="x_lim_min" type="xs:double"/>
            <xs:attribute name="x_log" type="xs:integer"/>
            <xs:attribute name="y_flip" type="xs:integer"/>
            <xs:attribute name="y_lim_max" type="xs:double"/>
            <xs:attribute name="y_lim_min" type="xs:double"/>
            <xs:attribute name="y_log" type="xs:integer"/>
            <xs:attribute name="z_flip" type="xs:integer"/>
            <xs:attribute name="z_lim_max" type="xs:double"/>
            <xs:attribute name="z_lim_min" type="xs:double"/>
            <xs:attribute name="z_log" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of marginal_heatmap_plot -->
    <xs:element name="marginal_heatmap_plot">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="central_region" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="side_region" minOccurs="0" maxOccurs="4"/>
                <xs:element ref="text" minOccurs="0" maxOccurs="1"/> <!-- title -->
            </xs:choice>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attribute name="algorithm" type="xs:string"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="marginal_heatmap_kind" type="xs:string" use="required"/>
            <xs:attribute name="x" type="xs:string" use="required"/>
            <xs:attribute name="x_ind" type="xs:integer"/>
            <xs:attribute name="y" type="xs:string" use="required"/>
            <xs:attribute name="y_ind" type="xs:integer"/>
            <xs:attribute name="z" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of central_region -->
    <xs:element name="central_region">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="coordinate_system" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="series_barplot" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_contour" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_contourf" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_heatmap" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_hexbin" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_histogram" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_imshow" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_isosurface" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_line" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_molecule" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_nonuniform_heatmap" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_nonuniform_polar_heatmap" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_pie" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_line3" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_polar_heatmap" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_polar_histogram" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_polar_line" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_polar_scatter" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_quiver" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_scatter" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_scatter3" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_shade" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_stairs" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_stem" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_surface" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_tricontour" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_trisurface" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_volume" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="series_wireframe" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attribute name="clip_region" type="xs:integer"/>
            <xs:attribute name="keep_window" type="xs:integer"/>
            <xs:attribute name="orientation" type="xs:string"/>
            <xs:attribute name="r_max" type="xs:double"/>
            <xs:attribute name="r_min" type="xs:double"/>
            <xs:attribute name="resample_method" type="strint"/>
            <xs:attribute name="select_specific_xform" type="xs:integer"/>
            <xs:attribute name="space_rotation" type="xs:integer"/>
            <xs:attribute name="space_tilt" type="xs:integer"/>
            <xs:attribute name="space_z_max" type="xs:double"/>
            <xs:attribute name="space_z_min" type="xs:double"/>
            <xs:attribute name="space_3d_camera_distance" type="xs:double"/>
            <xs:attribute name="space_3d_fov" type="xs:double"/>
            <xs:attribute name="space_3d_phi" type="xs:double"/>
            <xs:attribute name="space_3d_theta" type="xs:double"/>
            <xs:attribute name="tick" type="xs:double"/>
            <xs:attribute name="window_x_max" type="xs:double"/>
            <xs:attribute name="window_x_min" type="xs:double"/>
            <xs:attribute name="window_y_max" type="xs:double"/>
            <xs:attribute name="window_y_min" type="xs:double"/>
            <xs:attribute name="window_z_max" type="xs:double"/>
            <xs:attribute name="window_z_min" type="xs:double"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of side_region -->
    <xs:element name="side_region">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="side_plot_region" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="text_region" minOccurs="0" maxOccurs="1"/>
            </xs:choice>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attribute name="clip_region" type="xs:integer"/>
            <xs:attribute name="location" type="strint" use="required"/>
            <xs:attribute name="marginal_heatmap_side_plot" type="xs:integer"/>
            <xs:attribute name="text_content" type="xs:string"/>
            <xs:attribute name="text_is_title" type="xs:integer"/>
            <xs:attribute name="viewport_offset" type="xs:double"/>
            <xs:attribute name="width" type="xs:double"/>
            <xs:attribute name="window_x_max" type="xs:double"/>
            <xs:attribute name="window_x_min" type="xs:double"/>
            <xs:attribute name="window_y_max" type="xs:double"/>
            <xs:attribute name="window_y_min" type="xs:double"/>
            <xs:attribute name="x_flip" type="xs:integer"/>
            <xs:attribute name="y_flip" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of side_plot_region -->
    <xs:element name="side_plot_region">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="axis" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="colorbar" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="series_histogram" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="series_stairs" minOccurs="0" maxOccurs="1"/>
            </xs:choice>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attribute name="location" type="strint"/>
            <xs:attribute name="orientation" type="xs:string"/>
            <xs:attribute name="window_x_max" type="xs:double"/>
            <xs:attribute name="window_x_min" type="xs:double"/>
            <xs:attribute name="window_y_max" type="xs:double"/>
            <xs:attribute name="window_y_min" type="xs:double"/>
            <xs:attribute name="x_flip" type="xs:integer"/>
            <xs:attribute name="y_flip" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of text_region -->
    <xs:element name="text_region">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="text" minOccurs="0" maxOccurs="1"/>
            </xs:choice>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attribute name="location" type="strint"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of coordinate_system -->
    <xs:element name="coordinate_system">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="axes_3d" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="axis" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="grid_3d" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="theta_axes" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="polyline" minOccurs="0" maxOccurs="2"/>
                <xs:element ref="radial_axes" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="titles_3d" minOccurs="0" maxOccurs="1"/>
            </xs:choice>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attribute name="angle_ticks" type="xs:integer"/>
            <xs:attribute name="char_height" type="xs:double"/>
            <xs:attribute name="hide" type="xs:integer"/>
            <xs:attribute name="plot_type" type="xs:string"/>
            <xs:attribute name="theta_flip" type="xs:integer"/>
            <xs:attribute name="x_grid" type="xs:integer"/>
            <xs:attribute name="x_ind" type="xs:double"/>
            <xs:attribute name="x_label" type="xs:string"/>
            <xs:attribute name="y_grid" type="xs:integer"/>
            <xs:attribute name="y_line" type="xs:integer"/>
            <xs:attribute name="y_label" type="xs:string"/>
            <xs:attribute name="z_grid" type="xs:integer"/>
            <xs:attribute name="z_label" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of grid_3d -->
    <xs:element name="grid_3d">
        <xs:complexType>
            <xs:attributeGroup ref="grid"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="x_major" type="xs:integer" use="required"/>
            <xs:attribute name="x_origin_pos" type="xs:string" use="required"/>
            <xs:attribute name="y_major" type="xs:integer" use="required"/>
            <xs:attribute name="y_origin_pos" type="xs:string" use="required"/>
            <xs:attribute name="z_major" type="xs:integer"/>
            <xs:attribute name="z_origin_pos" type="xs:string"/>
            <xs:attribute name="z_tick" type="xs:double"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of axis -->
    <xs:element name="axis">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="polyline" minOccurs="0" maxOccurs="1"/> <!-- axis-line -->
                <xs:element ref="tick_group" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attribute name="adjust_x_lim" type="xs:integer"/>
            <xs:attribute name="adjust_y_lim" type="xs:integer"/>
            <xs:attribute name="axis_type" type="xs:string" use="required"/> <!-- X or Y -->
            <xs:attribute name="char_up_x" type="xs:double"/>
            <xs:attribute name="char_up_y" type="xs:double"/>
            <xs:attribute name="draw_grid" type="xs:integer"/>
            <xs:attribute name="label_orientation" type="xs:integer"/>
            <xs:attribute name="label_pos" type="xs:double"/>
            <xs:attribute name="location" type="strint"/>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="num_tick_labels" type="xs:integer"/>
            <xs:attribute name="num_ticks" type="xs:integer"/>
            <xs:attribute name="major_count" type="xs:integer"/>
            <xs:attribute name="max_value" type="xs:double"/>
            <xs:attribute name="min_value" type="xs:double"/>
            <xs:attribute name="mirrored_axis" type="xs:integer"/>
            <xs:attribute name="pos" type="xs:double"/>
            <xs:attribute name="origin" type="xs:double"/>
            <xs:attribute name="scale" type="xs:integer"/>
            <xs:attribute name="scientific_format" type="strint"/>
            <xs:attribute name="text_angle" type="xs:integer"/>
            <xs:attribute name="tick" type="xs:double"/>
            <xs:attribute name="tick_orientation" type="xs:integer"/>
            <xs:attribute name="tick_size" type="xs:double"/>
            <xs:attribute name="window_x_max" type="xs:double"/>
            <xs:attribute name="window_x_min" type="xs:double"/>
            <xs:attribute name="window_y_max" type="xs:double"/>
            <xs:attribute name="window_y_min" type="xs:double"/>
            <xs:attribute name="x_lim_max" type="xs:double"/>
            <xs:attribute name="x_lim_min" type="xs:double"/>
            <xs:attribute name="x_major" type="xs:integer"/> <!-- remove later -->
            <xs:attribute name="x_tick" type="xs:integer"/> <!-- remove later -->
            <xs:attribute name="y_lim_max" type="xs:double"/>
            <xs:attribute name="y_lim_min" type="xs:double"/>
            <xs:attribute name="y_major" type="xs:integer"/> <!-- remove later -->
            <xs:attribute name="y_tick" type="xs:integer"/> <!-- remove later -->
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of tick_group -->
    <xs:element name="tick_group">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="grid_line" minOccurs="0" maxOccurs="1"/> <!-- grid -->
                <xs:element ref="text" minOccurs="0" maxOccurs="2"/> <!-- tick label -->
                <xs:element ref="tick" minOccurs="0" maxOccurs="2"/> <!-- tick -->
            </xs:choice>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attributeGroup ref="text_modifications"/>
            <xs:attribute name="char_height" type="xs:double"/>
            <xs:attribute name="is_major" type="xs:integer"/>
            <xs:attribute name="scientific_format" type="strint"/>
            <xs:attribute name="tick_label" type="xs:string"/>
            <xs:attribute name="tick_size" type="xs:double"/>
            <xs:attribute name="value" type="xs:double"/>
            <xs:attribute name="width" type="xs:double"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of tick -->
    <xs:element name="tick">
        <xs:complexType>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="is_major" type="xs:integer"/>
            <xs:attribute name="is_mirrored" type="xs:integer"/>
            <xs:attribute name="value" type="xs:double"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of grid_line -->
    <xs:element name="grid_line">
        <xs:complexType>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="is_major" type="xs:integer"/>
            <xs:attribute name="value" type="xs:double"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of axes_3d -->
    <xs:element name="axes_3d">
        <xs:complexType>
            <xs:attributeGroup ref="axes"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="text_color" type="strint"/>
            <xs:attribute name="z_index" type="xs:integer"/>
            <xs:attribute name="z_major" type="xs:integer"/>
            <xs:attribute name="z_origin" type="xs:double"/>
            <xs:attribute name="z_origin_pos" type="xs:string"/>
            <xs:attribute name="z_tick" type="xs:double"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of title, label -->
    <xs:element name="text">
        <xs:complexType>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attributeGroup ref="text_modifications"/>
            <xs:attribute name="char_height" type="xs:double"/>
            <xs:attribute name="char_up_x" type="xs:double"/>
            <xs:attribute name="char_up_y" type="xs:double"/>
            <xs:attribute name="height" type="xs:double"/>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="scientific_format" type="strint"/>
            <xs:attribute name="set_text_color_for_background" type="xs:integer"/>
            <xs:attribute name="text" type="xs:string" use="required"/>
            <xs:attribute name="text_angle" type="xs:integer"/>
            <xs:attribute name="width" type="xs:double"/>
            <xs:attribute name="world_coordinates" type="xs:integer"/>
            <xs:attribute name="x" type="xs:double"/>
            <xs:attribute name="y" type="xs:double"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of titles_3d -->
    <xs:element name="titles_3d">
        <xs:complexType>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attribute name="text_color" type="strint"/>
            <xs:attribute name="x_label_3d" type="xs:string" use="required"/>
            <xs:attribute name="y_label_3d" type="xs:string" use="required"/>
            <xs:attribute name="z_label_3d" type="xs:string" use="required"/>
            <xs:attribute name="scientific_format" type="strint"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of legend -->
    <xs:element name="legend">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="draw_rect" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="fill_rect" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="label" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="fill_modifications"/>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attribute name="color_ind_values" type="xs:string"/>
            <xs:attribute name="color_rgb_values" type="xs:string"/>
            <xs:attribute name="location" type="strint"/>
            <xs:attribute name="scale" type="xs:integer"/>
            <xs:attribute name="select_specific_xform" type="xs:integer"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of label -->
    <xs:element name="label">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="draw_rect" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="fill_rect" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="polyline" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="polymarker" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="text" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="fill_modifications"/>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attributeGroup ref="text_modifications"/>
            <xs:attribute name="char_height" type="xs:double"/>
            <xs:attribute name="hidden" type="xs:integer"/>
            <xs:attribute name="transparency" type="xs:double"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of radial_axes -->
    <xs:element name="radial_axes">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="arc_grid_line" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="draw_arc" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="text" minOccurs="0" maxOccurs="1"/>
            </xs:choice>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="text_modifications"/>
            <xs:attribute name="scientific_format" type="strint"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of arc_grid_line -->
    <xs:element name="arc_grid_line">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="draw_arc" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="text" minOccurs="0" maxOccurs="1"/>
            </xs:choice>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="text_modifications"/>
            <xs:attribute name="arc_label" type="xs:string"/>
            <xs:attribute name="value" type="xs:double"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of theta_axes -->
    <xs:element name="theta_axes">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="angle_line" minOccurs="0" maxOccurs="8"/>
            </xs:choice>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="text_modifications"/>
            <xs:attribute name="angle_line_num" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of angle_line -->
    <xs:element name="angle_line">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="polyline" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="text" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="text_modifications"/>
            <xs:attribute name="angle_label" type="xs:string"/>
            <xs:attribute name="r" type="xs:double"/>
            <xs:attribute name="text_x0" type="xs:double"/>
            <xs:attribute name="text_y0" type="xs:double"/>
            <xs:attribute name="theta" type="xs:double"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of error_bars -->
    <xs:element name="error_bars">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="bar" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="error_bar" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="fill_area" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="fill_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="abs_downwards_e" type="xs:string"/>
            <xs:attribute name="abs_upwards_e" type="xs:string"/>
            <xs:attribute name="downwards_cap_color" type="xs:integer"/>
            <xs:attribute name="error_bar_color" type="xs:integer"/>
            <xs:attribute name="error_bar_style" type="xs:integer"/>
            <xs:attribute name="rel_downwards_e" type="xs:string"/>
            <xs:attribute name="rel_upwards_e" type="xs:string"/>
            <xs:attribute name="uniform_rel_upwards_e" type="xs:double"/>
            <xs:attribute name="uniform_abs_upwards_e" type="xs:double"/>
            <xs:attribute name="uniform_rel_downwards_e" type="xs:double"/>
            <xs:attribute name="uniform_abs_downwards_e" type="xs:double"/>
            <xs:attribute name="upwards_cap_color" type="xs:integer"/>
            <xs:attribute name="x" type="xs:string" use="required"/>
            <xs:attribute name="y" type="xs:string" use="required"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of polyline_3d -->
    <xs:element name="polyline_3d">
        <xs:complexType>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="polyline"/>
            <xs:attribute name="z" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of polyline -->
    <xs:element name="polyline">
        <xs:complexType>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="polyline"/>
            <xs:attribute name="transparency" type="xs:double"/>
            <xs:attribute name="x1" type="xs:double"/>
            <xs:attribute name="x2" type="xs:double"/>
            <xs:attribute name="y1" type="xs:double"/>
            <xs:attribute name="y2" type="xs:double"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of polymarker -->
    <xs:element name="polymarker">
        <xs:complexType>
            <xs:attributeGroup ref="marker_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="polymarker"/>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of polymarker_3d -->
    <xs:element name="polymarker_3d">
        <xs:complexType>
            <xs:attributeGroup ref="marker_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="polymarker"/>
            <xs:attribute name="z" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of fill_rect -->
    <xs:element name="fill_rect">
        <xs:complexType>
            <xs:attributeGroup ref="fill_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="rect"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of draw_rect -->
    <xs:element name="draw_rect">
        <xs:complexType>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="rect"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of colorbar -->
    <xs:element name="colorbar">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="axis" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="cell_array" minOccurs="0" maxOccurs="1"/>
            </xs:choice>
            <xs:attributeGroup ref="move_xform_ndc"/>
            <xs:attribute name="char_height" type="xs:double"/>
            <xs:attribute name="num_color_values" type="xs:integer"/>
            <xs:attribute name="x_flip" type="xs:integer"/>
            <xs:attribute name="y_flip" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of cell_array -->
    <xs:element name="cell_array">
        <xs:complexType>
            <xs:attributeGroup ref="cell_array"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="x_dim" type="xs:integer" use="required"/>
            <xs:attribute name="x_max" type="xs:double" use="required"/>
            <xs:attribute name="x_min" type="xs:double" use="required"/>
            <xs:attribute name="y_dim" type="xs:integer" use="required"/>
            <xs:attribute name="y_max" type="xs:double" use="required"/>
            <xs:attribute name="y_min" type="xs:double" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of nonuniform_cell_array -->
    <xs:element name="nonuniform_cell_array">
        <xs:complexType>
            <xs:attributeGroup ref="cell_array"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="x" type="xs:string" use="required"/>
            <xs:attribute name="x_dim" type="xs:integer" use="required"/>
            <xs:attribute name="y" type="xs:string" use="required"/>
            <xs:attribute name="y_dim" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of polar_cell_array -->
    <xs:element name="polar_cell_array">
        <xs:complexType>
            <xs:attributeGroup ref="cell_array"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="r_dim" type="xs:integer" use="required"/>
            <xs:attribute name="r_max" type="xs:double" use="required"/>
            <xs:attribute name="r_min" type="xs:double" use="required"/>
            <xs:attribute name="r_org" type="xs:double" use="required"/>
            <xs:attribute name="theta_dim" type="xs:integer" use="required"/>
            <xs:attribute name="theta_max" type="xs:double" use="required"/>
            <xs:attribute name="theta_min" type="xs:double" use="required"/>
            <xs:attribute name="theta_org" type="xs:double" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of nonuniform_polar_cell_array -->
    <xs:element name="nonuniform_polar_cell_array">
        <xs:complexType>
            <xs:attributeGroup ref="cell_array"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="r" type="xs:string" use="required"/>
            <xs:attribute name="r_dim" type="xs:integer" use="required"/>
            <xs:attribute name="r_org" type="xs:double" use="required"/>
            <xs:attribute name="theta" type="xs:string" use="required"/>
            <xs:attribute name="theta_dim" type="xs:integer" use="required"/>
            <xs:attribute name="theta_org" type="xs:double" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of draw_image -->
    <xs:element name="draw_image">
        <xs:complexType>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="color_model" type="strint" use="required"/>
            <xs:attribute name="data" type="xs:string" use="required"/>
            <xs:attribute name="height" type="xs:integer" use="required"/>
            <xs:attribute name="resample_method" type="strint"/>
            <xs:attribute name="width" type="xs:integer" use="required"/>
            <xs:attribute name="x_max" type="xs:double" use="required"/>
            <xs:attribute name="x_min" type="xs:double" use="required"/>
            <xs:attribute name="y_max" type="xs:double" use="required"/>
            <xs:attribute name="y_min" type="xs:double" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of draw_arc -->
    <xs:element name="draw_arc">
        <xs:complexType>
            <xs:attributeGroup ref="arc"/>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of fill_arc -->
    <xs:element name="fill_arc">
        <xs:complexType>
            <xs:attributeGroup ref="arc"/>
            <xs:attributeGroup ref="fill_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of fill_area -->
    <xs:element name="fill_area">
        <xs:complexType>
            <xs:attributeGroup ref="fill_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="transparency" type="xs:double"/>
            <xs:attribute name="x" type="xs:string" use="required"/>
            <xs:attribute name="y" type="xs:string" use="required"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of cylinder -->
    <xs:element name="cylinder">
        <xs:complexType>
            <xs:attribute name="color_rgb_values" type="xs:string" use="required"/>
            <xs:attribute name="length" type="xs:double" use="required"/>
            <xs:attribute name="radius" type="xs:double"/>
            <xs:attribute name="x" type="xs:double" use="required"/>
            <xs:attribute name="x_dir" type="xs:double" use="required"/>
            <xs:attribute name="y" type="xs:double" use="required"/>
            <xs:attribute name="y_dir" type="xs:double" use="required"/>
            <xs:attribute name="z" type="xs:double" use="required"/>
            <xs:attribute name="z_dir" type="xs:double" use="required"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of sphere -->
    <xs:element name="sphere">
        <xs:complexType>
            <xs:attribute name="fill_color" type="xs:string" use="required"/>
            <xs:attribute name="radius" type="xs:double" use="required"/>
            <xs:attribute name="symbol" type="xs:string" use="required"/>
            <xs:attribute name="x" type="xs:double" use="required"/>
            <xs:attribute name="y" type="xs:double" use="required"/>
            <xs:attribute name="z" type="xs:double" use="required"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of spin -->
    <xs:element name="spin">
        <xs:complexType>
            <xs:attribute name="fill_color" type="xs:string" use="required"/>
            <xs:attribute name="length" type="xs:double" use="required"/>
            <xs:attribute name="symbol" type="xs:string" use="required"/>
            <xs:attribute name="x" type="xs:double" use="required"/>
            <xs:attribute name="x_dir" type="xs:double" use="required"/>
            <xs:attribute name="y" type="xs:double" use="required"/>
            <xs:attribute name="y_dir" type="xs:double" use="required"/>
            <xs:attribute name="z" type="xs:double" use="required"/>
            <xs:attribute name="z_dir" type="xs:double" use="required"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of gr3_draw_image -->
    <xs:element name="gr3_draw_image">
        <xs:complexType>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- ||||||||||||||||||||||||||||| Plottypes |||||||||||||||||||||||||||||||||||||||| -->

    <!-- definition of barplot -->
    <xs:element name="series_barplot">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="bar" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="error_bars" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="fill_modifications"/>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
            <xs:attributeGroup ref="text_modifications"/>
            <xs:attribute name="bar_width" type="xs:double"/>
            <xs:attribute name="color_ind_values" type="xs:string"/>
            <xs:attribute name="color_rgb_values" type="xs:string"/>
            <xs:attribute name="edge_width" type="xs:double"/>
            <xs:attribute name="indices" type="xs:string"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="label" type="xs:string"/>
            <xs:attribute name="series_index" type="xs:integer"/>
            <xs:attribute name="style" type="xs:string"/>
            <xs:attribute name="transparency" type="xs:double"/>
            <xs:attribute name="x" type="xs:string"/>
            <xs:attribute name="y" type="xs:string" use="required"/>
            <xs:attribute name="y_labels" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of contour -->
    <xs:element name="series_contour">
        <xs:complexType>
            <xs:attributeGroup ref="contour"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="series"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of contourf -->
    <xs:element name="series_contourf">
        <xs:complexType>
            <xs:attributeGroup ref="contour"/>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="series"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of heatmap -->
    <xs:element name="series_heatmap">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="draw_image" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="nonuniform_cell_array" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="heatmap"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of hexbin -->
    <xs:element name="series_hexbin">
        <xs:complexType>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="num_bins" type="xs:integer"/>
            <xs:attribute name="x" type="xs:string" use="required"/>
            <xs:attribute name="y" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of histogram -->
    <xs:element name="series_histogram">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="bar" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="error_bars" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="fill_modifications"/>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="bins" type="xs:string"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="num_bins" type="xs:integer"/>
            <xs:attribute name="transparency" type="xs:double"/>
            <xs:attribute name="weights" type="xs:string"/>
            <xs:attribute name="x" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of imshow -->
    <xs:element name="series_imshow">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="cell_array" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="data" type="xs:string"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="scale" type="xs:integer"/>
            <xs:attribute name="select_specific_xform" type="xs:integer"/>
            <xs:attribute name="x" type="xs:string"/>
            <xs:attribute name="y" type="xs:string"/>
            <xs:attribute name="z" type="xs:string" use="required"/>
            <xs:attribute name="z_dims" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of isosurface -->
    <xs:element name="series_isosurface">
        <xs:complexType>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="ambient" type="xs:double"/>
            <xs:attribute name="diffuse" type="xs:double"/>
            <!-- `d_min` and `d_max` must only be set if a volume was switched
                to an isosurface (so it can be switched back) -->
            <xs:attribute name="d_max" type="xs:double"/>
            <xs:attribute name="d_min" type="xs:double"/>
            <xs:attribute name="fill_color" type="xs:string"/>
            <xs:attribute name="isovalue" type="xs:double"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="specular" type="xs:double"/>
            <xs:attribute name="specular_power" type="xs:double"/>
            <xs:attribute name="z" type="xs:string" use="required"/>
            <xs:attribute name="z_dims" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of line -->
    <xs:element name="series_line">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="error_bars" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="integral_group" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="polyline" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="polymarker" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="marker_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="label" type="xs:string"/>
            <xs:attribute name="x" type="xs:string"/>
            <xs:attribute name="y" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of nonuniform_heatmap -->
    <xs:element name="series_nonuniform_heatmap">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="series_heatmap" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="series"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of nonuniform_polar_heatmap -->
    <xs:element name="series_nonuniform_polar_heatmap">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="series_polar_heatmap" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="series"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of pie -->
    <xs:element name="series_pie">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="pie_segment" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="fill_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
            <xs:attributeGroup ref="text_modifications"/>
            <xs:attribute name="color_ind_values" type="xs:string"/>
            <xs:attribute name="color_rgb_values" type="xs:string"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="labels" type="xs:string"/>
            <xs:attribute name="x" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of line3 -->
    <xs:element name="series_line3">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="polyline_3d" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="label" type="xs:string"/>
            <xs:attribute name="x" type="xs:string" use="required"/>
            <xs:attribute name="y" type="xs:string" use="required"/>
            <xs:attribute name="z" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of molecule -->
    <xs:element name="series_molecule">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="cylinder" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="gr3_draw_image" minOccurs="0" maxOccurs="1"/> <!-- just for internal usage -->
                <xs:element ref="unit_cell" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="sphere" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="spin" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="draw_image" minOccurs="0" maxOccurs="1"/> <!-- contourf -->
            </xs:choice>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attribute name="ambient" type="xs:double"/>
            <xs:attribute name="cell" type="xs:string"/>
            <xs:attribute name="color_rgb_values" type="xs:string"/>
            <xs:attribute name="color_scheme" type="xs:integer"/>
            <xs:attribute name="connection_threshold" type="xs:double"/>
            <xs:attribute name="diffuse" type="xs:double"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="molecule_symbols" type="xs:string"/>
            <xs:attribute name="move_to_plot" type="xs:string"/>
            <xs:attribute name="radius_kind" type="xs:integer"/>
            <xs:attribute name="show_unit_cell" type="xs:integer"/>
            <xs:attribute name="specular" type="xs:double"/>
            <xs:attribute name="specular_power" type="xs:double"/>
            <xs:attribute name="spin_style" type="xs:integer"/>
            <xs:attribute name="spin_x" type="xs:string"/>
            <xs:attribute name="spin_y" type="xs:string"/>
            <xs:attribute name="spin_z" type="xs:string"/>
            <xs:attribute name="unified_connection_radius" type="xs:integer"/>
            <xs:attribute name="x" type="xs:string"/>
            <xs:attribute name="y" type="xs:string"/>
            <xs:attribute name="z" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of polar_heatmap -->
    <xs:element name="series_polar_heatmap">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="nonuniform_polar_cell_array" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="polar_cell_array" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="r" type="xs:string"/>
            <xs:attribute name="r_range_max" type="xs:double"/>
            <xs:attribute name="r_range_min" type="xs:double"/>
            <xs:attribute name="theta" type="xs:string"/>
            <xs:attribute name="theta_range_max" type="xs:double"/>
            <xs:attribute name="theta_range_min" type="xs:double"/>
            <xs:attribute name="z" type="xs:string" use="required"/>
            <xs:attribute name="z_dims" type="xs:string"/>
            <xs:attribute name="z_range_max" type="xs:double"/>
            <xs:attribute name="z_range_min" type="xs:double"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of polar_histogram -->
    <xs:element name="series_polar_histogram">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="draw_arc" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="polar_bar" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="polyline" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="fill_modifications"/>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="bin_counts" type="xs:string"/>
            <xs:attribute name="bin_edges" type="xs:string"/>
            <xs:attribute name="bin_width" type="xs:double"/>
            <xs:attribute name="bin_widths" type="xs:string"/>
            <xs:attribute name="counts" type="xs:string"/>
            <xs:attribute name="draw_edges" type="xs:integer"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="norm" type="xs:string"/>
            <xs:attribute name="num_bins" type="xs:integer"/>
            <xs:attribute name="r_max" type="xs:double"/>
            <xs:attribute name="r_min" type="xs:double"/>
            <xs:attribute name="r_range_max" type="xs:double"/>
            <xs:attribute name="r_range_min" type="xs:double"/>
            <xs:attribute name="stairs" type="xs:integer"/>
            <xs:attribute name="tick" type="xs:double"/>
            <xs:attribute name="transparency" type="xs:double"/>
            <xs:attribute name="theta" type="xs:string"/>
            <xs:attribute name="theta_data_lim_max" type="xs:double"/>
            <xs:attribute name="theta_data_lim_min" type="xs:double"/>
            <xs:attribute name="theta_range_max" type="xs:double"/>
            <xs:attribute name="theta_range_min" type="xs:double"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of polar_line -->
    <xs:element name="series_polar_line">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="polyline" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="polymarker" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="marker_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="clip_negative" type="xs:int"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="label" type="xs:string"/>
            <xs:attribute name="r" type="xs:string" use="required"/>
            <xs:attribute name="r_max" type="xs:double"/>
            <xs:attribute name="r_min" type="xs:double"/>
            <xs:attribute name="r_range_max" type="xs:double"/>
            <xs:attribute name="r_range_min" type="xs:double"/>
            <xs:attribute name="theta" type="xs:string" use="required"/>
            <xs:attribute name="theta_range_max" type="xs:double"/>
            <xs:attribute name="theta_range_min" type="xs:double"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of polar_scatter -->
    <xs:element name="series_polar_scatter">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="polymarker" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="marker_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="clip_negative" type="xs:int"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="label" type="xs:string"/>
            <xs:attribute name="r" type="xs:string" use="required"/>
            <xs:attribute name="r_max" type="xs:double"/>
            <xs:attribute name="r_min" type="xs:double"/>
            <xs:attribute name="r_range_max" type="xs:double"/>
            <xs:attribute name="r_range_min" type="xs:double"/>
            <xs:attribute name="theta" type="xs:string" use="required"/>
            <xs:attribute name="theta_range_max" type="xs:double"/>
            <xs:attribute name="theta_range_min" type="xs:double"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of quiver -->
    <xs:element name="series_quiver">
        <xs:complexType>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="colored" type="xs:integer" use="required"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="u" type="xs:string" use="required"/>
            <xs:attribute name="v" type="xs:string" use="required"/>
            <xs:attribute name="x" type="xs:string" use="required"/>
            <xs:attribute name="y" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of scatter -->
    <xs:element name="series_scatter">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="error_bars" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="polymarker" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="marker_modifications"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="scatter"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="label" type="xs:string"/>
            <xs:attribute name="z" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of scatter3 -->
    <xs:element name="series_scatter3">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="polymarker_3d" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="marker_modifications"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="scatter"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="label" type="xs:string"/>
            <xs:attribute name="z" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of shade -->
    <xs:element name="series_shade">
        <xs:complexType>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="transformation" type="xs:integer"/>
            <xs:attribute name="x" type="xs:string" use="required"/>
            <xs:attribute name="x_bins" type="xs:integer"/>
            <xs:attribute name="y" type="xs:string" use="required"/>
            <xs:attribute name="y_bins" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of stairs -->
    <xs:element name="series_stairs">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="polyline" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="polymarker" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="label" type="xs:string"/>
            <xs:attribute name="step_where" type="xs:string"/>
            <xs:attribute name="x" type="xs:string" use="required"/>
            <xs:attribute name="y" type="xs:string" use="required"/>
            <xs:attribute name="z" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of stem -->
    <xs:element name="series_stem">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="polyline" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="polymarker" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="label" type="xs:string"/>
            <xs:attribute name="marker_color" type="strint"/>
            <xs:attribute name="x" type="xs:string" use="required"/>
            <xs:attribute name="y" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of surface -->
    <xs:element name="series_surface">
        <xs:complexType>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="use_gr3" type="xs:integer" use="required"/>
            <xs:attribute name="x" type="xs:string"/>
            <xs:attribute name="y" type="xs:string"/>
            <xs:attribute name="z" type="xs:string" use="required"/>
            <xs:attribute name="z_dims" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of tricontour -->
    <xs:element name="series_tricontour">
        <xs:complexType>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="levels" type="xs:integer" use="required"/>
            <xs:attribute name="x" type="xs:string" use="required"/>
            <xs:attribute name="y" type="xs:string" use="required"/>
            <xs:attribute name="z" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of trisurface -->
    <xs:element name="series_trisurface">
        <xs:complexType>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="x" type="xs:string" use="required"/>
            <xs:attribute name="y" type="xs:string" use="required"/>
            <xs:attribute name="z" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of volume -->
    <xs:element name="series_volume">
        <xs:complexType>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="algorithm" type="strint" use="required"/>
            <xs:attribute name="d_max" type="xs:double"/>
            <xs:attribute name="d_min" type="xs:double"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="z" type="xs:string" use="required"/>
            <xs:attribute name="z_dims" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of wireframe -->
    <xs:element name="series_wireframe">
        <xs:complexType>
            <xs:attributeGroup ref="fill_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attributeGroup ref="ranges"/>
            <xs:attributeGroup ref="series"/>
            <xs:attribute name="kind" type="xs:string"/>
            <xs:attribute name="x" type="xs:string" use="required"/>
            <xs:attribute name="y" type="xs:string" use="required"/>
            <xs:attribute name="z" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- ||||||||||||||||||||||||||||| series subgroups |||||||||||||||||||||||||||||||||||||||| -->

    <!-- definition of error_bar -->
    <xs:element name="error_bar">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="3">
                <xs:element ref="polyline" minOccurs="0" maxOccurs="3"/>
            </xs:choice>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="cap_x_max" type="xs:double"/>
            <xs:attribute name="cap_x_min" type="xs:double"/>
            <xs:attribute name="downwards_cap_color" type="xs:integer"/>
            <xs:attribute name="downwards_e" type="xs:double"/>
            <xs:attribute name="error_bar_color" type="xs:integer" use="required"/>
            <xs:attribute name="error_bar_x" type="xs:double" use="required"/>
            <xs:attribute name="error_bar_y_max" type="xs:double" use="required"/>
            <xs:attribute name="error_bar_y_min" type="xs:double" use="required"/>
            <xs:attribute name="upwards_cap_color" type="xs:integer"/>
            <xs:attribute name="upwards_e" type="xs:double"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of bar -->
    <xs:element name="bar">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="draw_rect" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="fill_rect" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="text" minOccurs="0" maxOccurs="1"/>
            </xs:choice>
            <xs:attributeGroup ref="fill_modifications"/>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="text" type="xs:string"/>
            <xs:attribute name="x1" type="xs:double" use="required"/>
            <xs:attribute name="x2" type="xs:double" use="required"/>
            <xs:attribute name="y1" type="xs:double" use="required"/>
            <xs:attribute name="y2" type="xs:double" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of integral -->
    <xs:element name="integral">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="fill_area" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="polyline" minOccurs="0" maxOccurs="2"/>
            </xs:choice>
            <xs:attributeGroup ref="fill_modifications"/>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="int_lim_high" type="xs:double" use="required"/>
            <xs:attribute name="int_lim_low" type="xs:double" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of integral_group -->
    <xs:element name="integral_group">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="integral" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attributeGroup ref="fill_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="int_limits_high" type="xs:string" use="required"/>
            <xs:attribute name="int_limits_low" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of polar_bar -->
    <xs:element name="polar_bar">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="2">
                <xs:element ref="fill_area" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="fill_arc" minOccurs="0" maxOccurs="1"/>
            </xs:choice>
            <xs:attributeGroup ref="fill_modifications"/>
            <xs:attributeGroup ref="line_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="bin_edges" type="xs:string"/>
            <xs:attribute name="bin_nr" type="xs:integer" use="required"/>
            <xs:attribute name="bin_width" type="xs:double"/>
            <xs:attribute name="bin_widths" type="xs:double"/>
            <xs:attribute name="count" type="xs:double" use="required"/>
            <xs:attribute name="draw_edges" type="xs:integer"/>
            <xs:attribute name="norm" type="xs:string"/>
            <xs:attribute name="theta_flip" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of pie_segment -->
    <xs:element name="pie_segment">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="fill_arc" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="text" minOccurs="0" maxOccurs="1"/>
            </xs:choice>
            <xs:attributeGroup ref="fill_modifications"/>
            <xs:attributeGroup ref="move_xform_wc"/>
            <xs:attribute name="end_angle" type="xs:double" use="required"/>
            <xs:attribute name="start_angle" type="xs:double" use="required"/>
            <xs:attribute name="text" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- definition of unit_cell -->
    <xs:element name="unit_cell">
        <xs:complexType>
            <xs:attribute name="fill_color" type="xs:string"/>
            <xs:attribute name="line_color" type="xs:string"/>
            <xs:attribute name="show_mesh" type="xs:integer"/>
            <xs:attribute name="transparency" type="xs:double"/>
            <xs:attribute name="z_index" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <!-- ||||||||||||||||||||||||||||| attribute groups |||||||||||||||||||||||||||||||||||||||| -->

    <!-- definition of move_xform_wc attributes -->
    <xs:attributeGroup name="move_xform_wc">
        <xs:attribute name="disable_x_trans" type="xs:integer"/>
        <xs:attribute name="disable_y_trans" type="xs:integer"/>
        <xs:attribute name="movable" type="xs:integer"/>
        <xs:attribute name="x_max_shift_wc" type="xs:double"/>
        <xs:attribute name="x_min_shift_wc" type="xs:double"/>
        <xs:attribute name="x_shift_wc" type="xs:double"/>
        <xs:attribute name="y_max_shift_wc" type="xs:double"/>
        <xs:attribute name="y_min_shift_wc" type="xs:double"/>
        <xs:attribute name="y_shift_wc" type="xs:double"/>
    </xs:attributeGroup>

    <!-- definition of move_xform_ndc attributes -->
    <xs:attributeGroup name="move_xform_ndc">
        <xs:attribute name="viewport_x_max" type="xs:double"/>
        <xs:attribute name="viewport_x_min" type="xs:double"/>
        <xs:attribute name="viewport_y_max" type="xs:double"/>
        <xs:attribute name="viewport_y_min" type="xs:double"/>
        <xs:attribute name="x_max_shift_ndc" type="xs:double"/>
        <xs:attribute name="x_min_shift_ndc" type="xs:double"/>
        <xs:attribute name="x_shift_ndc" type="xs:double"/>
        <xs:attribute name="y_max_shift_ndc" type="xs:double"/>
        <xs:attribute name="y_min_shift_ndc" type="xs:double"/>
        <xs:attribute name="y_shift_ndc" type="xs:double"/>
    </xs:attributeGroup>

    <!-- definition of range attributes -->
    <xs:attributeGroup name="ranges">
        <xs:attribute name="x_range_max" type="xs:double"/>
        <xs:attribute name="x_range_min" type="xs:double"/>
        <xs:attribute name="y_range_max" type="xs:double"/>
        <xs:attribute name="y_range_min" type="xs:double"/>
        <xs:attribute name="z_range_max" type="xs:double"/>
        <xs:attribute name="z_range_min" type="xs:double"/>
        <xs:attribute name="c_range_max" type="xs:double"/>
        <xs:attribute name="c_range_min" type="xs:double"/>
    </xs:attributeGroup>

    <!-- definition of contour attributes -->
    <xs:attributeGroup name="contour">
        <xs:attributeGroup ref="ranges"/>
        <xs:attribute name="kind" type="xs:string"/>
        <xs:attribute name="levels" type="xs:integer"/>
        <xs:attribute name="major_h" type="xs:integer"/>
        <xs:attribute name="px" type="xs:string"/>
        <xs:attribute name="py" type="xs:string"/>
        <xs:attribute name="pz" type="xs:string"/>
        <xs:attribute name="x" type="xs:string" use="required"/>
        <xs:attribute name="y" type="xs:string" use="required"/>
        <xs:attribute name="z" type="xs:string" use="required"/>
        <xs:attribute name="z_max" type="xs:double"/>
        <xs:attribute name="z_min" type="xs:double"/>
    </xs:attributeGroup>

    <!-- definition of axes attributes -->
    <xs:attributeGroup name="axes">
        <xs:attribute name="tick_orientation" type="xs:integer" use="required"/>
        <xs:attribute name="tick_size" type="xs:double"/>
        <xs:attribute name="x_major" type="xs:integer"/>
        <xs:attribute name="x_origin" type="xs:double"/>
        <xs:attribute name="x_origin_pos" type="xs:string"/>
        <xs:attribute name="x_tick" type="xs:double"/>
        <xs:attribute name="y_major" type="xs:integer"/>
        <xs:attribute name="y_origin" type="xs:double"/>
        <xs:attribute name="y_origin_pos" type="xs:string"/>
        <xs:attribute name="y_tick" type="xs:double"/>
    </xs:attributeGroup>

    <!-- definition of arc attributes -->
    <xs:attributeGroup name="arc">
        <xs:attribute name="end_angle" type="xs:double" use="required"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="start_angle" type="xs:double" use="required"/>
        <xs:attribute name="x_max" type="xs:double" use="required"/>
        <xs:attribute name="x_min" type="xs:double" use="required"/>
        <xs:attribute name="y_max" type="xs:double" use="required"/>
        <xs:attribute name="y_min" type="xs:double" use="required"/>
    </xs:attributeGroup>

    <!-- definition of grid attributes -->
    <xs:attributeGroup name="grid">
        <xs:attribute name="x_origin" type="xs:double"/>
        <xs:attribute name="x_tick" type="xs:double"/>
        <xs:attribute name="y_origin" type="xs:double"/>
        <xs:attribute name="y_tick" type="xs:double"/>
    </xs:attributeGroup>

    <!-- definition of heatmap attributes -->
    <xs:attributeGroup name="heatmap">
        <xs:attribute name="kind" type="xs:string"/>
        <xs:attribute name="x" type="xs:string"/>
        <xs:attribute name="y" type="xs:string"/>
        <xs:attribute name="z" type="xs:string" use="required"/>
        <xs:attribute name="z_dims" type="xs:string"/>
    </xs:attributeGroup>

    <!-- definition of polyline attributes -->
    <xs:attributeGroup name="polyline">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="x" type="xs:string"/>
        <xs:attribute name="y" type="xs:string"/>
    </xs:attributeGroup>

    <!-- definition of polymarker attributes -->
    <xs:attributeGroup name="polymarker">
        <xs:attribute name="x" type="xs:string"/>
        <xs:attribute name="y" type="xs:string"/>
    </xs:attributeGroup>

    <!-- definition of rect attributes -->
    <xs:attributeGroup name="rect">
        <xs:attribute name="x" type="xs:string"/>
        <xs:attribute name="y" type="xs:string"/>
        <xs:attribute name="x_max" type="xs:double" use="required"/>
        <xs:attribute name="x_min" type="xs:double" use="required"/>
        <xs:attribute name="y_max" type="xs:double" use="required"/>
        <xs:attribute name="y_min" type="xs:double" use="required"/>
    </xs:attributeGroup>

    <!-- definition of cell_array attributes -->
    <xs:attributeGroup name="cell_array">
        <xs:attribute name="clip_region" type="xs:integer"/>
        <xs:attribute name="color_ind_values" type="xs:string" use="required"/>
        <xs:attribute name="num_col" type="xs:integer" use="required"/>
        <xs:attribute name="num_row" type="xs:integer" use="required"/>
        <xs:attribute name="select_specific_xform" type="xs:integer"/>
        <xs:attribute name="start_col" type="xs:integer" use="required"/>
        <xs:attribute name="start_row" type="xs:integer" use="required"/>
    </xs:attributeGroup>

    <!-- definition of scatter attributes -->
    <xs:attributeGroup name="scatter">
        <xs:attribute name="c" type="xs:string"/>
        <xs:attribute name="color_rgb_values" type="xs:string"/>
        <xs:attribute name="kind" type="xs:string"/>
        <xs:attribute name="x" type="xs:string" use="required"/>
        <xs:attribute name="y" type="xs:string" use="required"/>
    </xs:attributeGroup>

    <!-- definition of series attributes -->
    <xs:attributeGroup name="series">
        <xs:attribute name="move_to_plot" type="xs:string"/>
        <xs:attribute name="ref_x_axis_location" type="strint"/>
        <xs:attribute name="ref_y_axis_location" type="strint"/>
    </xs:attributeGroup>

    <!-- definition of line_modifications attributes -->
    <xs:attributeGroup name="line_modifications">
        <xs:attribute name="line_color" type="strint"/> <!-- either an index or rgb ref -->
        <xs:attribute name="line_spec" type="xs:string"/>
        <xs:attribute name="line_type" type="strint"/>
        <xs:attribute name="line_width" type="xs:double"/>
    </xs:attributeGroup>

    <!-- definition of fill_modifications attributes -->
    <xs:attributeGroup name="fill_modifications">
        <xs:attribute name="fill_color" type="strint"/> <!-- either an index or rgb ref -->
        <xs:attribute name="fill_int_style" type="strint"/>
        <xs:attribute name="fill_style" type="strint"/>
    </xs:attributeGroup>

    <!-- definition of text_modifications attributes -->
    <xs:attributeGroup name="text_modifications">
        <xs:attribute name="font" type="strint"/>
        <xs:attribute name="font_precision" type="strint"/>
        <xs:attribute name="text_align_horizontal" type="strint"/>
        <xs:attribute name="text_align_vertical" type="strint"/>
        <xs:attribute name="text_color" type="strint"/> <!-- either an index or rgb ref -->
    </xs:attributeGroup>

    <!-- definition of marker_modifications attributes -->
    <xs:attributeGroup name="marker_modifications">
        <xs:attribute name="border_color" type="strint"/>
        <xs:attribute name="border_width" type="xs:double"/>
        <xs:attribute name="marker_color" type="strint"/> <!-- either an index or rgb ref -->
        <xs:attribute name="marker_color_indices" type="xs:string"/>
        <xs:attribute name="marker_size" type="xs:double"/>
        <xs:attribute name="marker_sizes" type="xs:string"/>
        <xs:attribute name="marker_type" type="strint"/>
    </xs:attributeGroup>

    <!-- ||||||||||||||||||||||||||||| simple types |||||||||||||||||||||||||||||||||||||||| -->

    <!-- definition of string and int type -->
    <xs:simpleType name="strint">
        <xs:union memberTypes="xs:string xs:integer"/>
    </xs:simpleType>
</xs:schema>

