#!/bin/sh
case $1 in
  test)
    version=`git describe | awk -F- '{print $1}' | sed 's/^v//'`
    cat recipe/meta.yaml.$1 | sed "s/VERSION/${version}/g" >recipe/meta.yaml
    ;;
  in)
    version=`cat version.txt | awk -F- '{print $1}' | sed 's/^v//'` || exit 1
    md5=`md5 -q dist/gr-${version}.tar.gz` || exit 1
    cat recipe/meta.yaml.$1 | sed "s/VERSION/${version}/g" | sed "s/MD5/${md5}/" >recipe/meta.yaml
    ;;
esac
