GRDIR = /usr/local/gr

self:
	$(MAKE) -C lib/gks
	$(MAKE) -C lib/gks/plugin
	$(MAKE) -C lib/gr
	$(MAKE) -C lib/gr3
	$(MAKE) -C lib/grm

clean:
	$(MAKE) -C lib/gks clean
	$(MAKE) -C lib/gks/plugin clean
	$(MAKE) -C lib/gr clean
	$(MAKE) -C lib/gr3 clean
	$(MAKE) -C lib/grm clean

.PHONY: clean self
