packages-tar:
  stage: package
  image: ubuntu:20.04
  variables:
    GIT_STRATEGY: none
  script:
  - has_release_tag="$(grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$' <<< "${CI_COMMIT_TAG}" && echo 1 || echo 0)"
  - if (( has_release_tag )); then
      version="${CI_COMMIT_TAG/#v/}";
    else
      version="${CI_COMMIT_SHA}";
    fi
  - mkdir Downloads
  - |-
    for artifact_target_pair in \
      "artifacts-windows-32bit      | Windows-i686" \
      "artifacts-windows-64bit      | Windows-x86_64" \
      "artifacts-windows-64bit-msvc | Windows-x86_64-msvc" \
      "artifacts-debian10           | Debian-x86_64" \
      "artifacts-debian10-armhf     | Debian-armhf" \
      "artifacts-debian10-aarch64   | Debian-aarch64" \
      "artifacts-ubuntu2004         | Ubuntu-x86_64" \
      "artifacts-centos7            | CentOS-x86_64" \
      "artifacts-centos7-32bit      | CentOS-i386" \
      "artifacts-arch               | ArchLinux-x86_64" \
      "artifacts-freebsd13          | FreeBSD-x86_64" \
      "artifacts-darwin-x86_64      | Darwin-x86_64" \
      "artifacts-darwin-aarch64     | Darwin-aarch64" \
      "artifacts-darwin-universal   | Darwin-universal"
    do
      artifact_dirname=$(awk -F'[[:space:]]*\\|[[:space:]]*' '{ print $1 }' <<< "${artifact_target_pair}") && \
      target_dirname=$(awk -F'[[:space:]]*\\|[[:space:]]*' '{ print $2 }' <<< "${artifact_target_pair}") && \
      echo "Packing $(awk -F'\\|' '{ print $1 }' <<< "${artifact_target_pair}") -> ${target_dirname}" && \
      mkdir "${target_dirname}" && \
      mv "${artifact_dirname}" "${target_dirname}/gr" && \
      cp artifacts-js/gr.js "${target_dirname}/gr/lib/" && \
      tar -C "${target_dirname}" -czf "${target_dirname}/gr.tar.gz" --remove-files gr && \
      mv "${target_dirname}/gr.tar.gz" "Downloads/gr-${version}-${target_dirname}.tar.gz" || exit
      if ! (( has_release_tag )); then
        ln -s "gr-${version}-${target_dirname}.tar.gz" "Downloads/gr-latest-${target_dirname}.tar.gz" || exit
      fi
    done
  - cp artifacts-js/gr.js "Downloads/gr-${version}.js"
  - if ! (( has_release_tag )); then
      ln -s "gr-${version}.js" "Downloads/gr-latest.js";
    fi
  - for alias in Redhat Linux; do
      for arch in x86_64 i386; do
        ln -s "gr-${version}-CentOS-${arch}.tar.gz" "Downloads/gr-${version}-${alias}-${arch}.tar.gz";
      done;
    done
  - (
      cd Downloads &&
      sha512sum -b gr-*.tar.gz gr-*.js > "gr-${version}.sha512.txt" &&
      if ! (( has_release_tag )); then
        ln -s "gr-${version}.sha512.txt" gr-latest.sha512.txt;
      fi
    )
  artifacts:
    expire_in: 1 week
    paths:
    - Downloads/
