######################################################################
# Automatically generated by qmake (3.1) Thu Feb 21 11:28:57 2019
######################################################################

GRDIR = $$(GRDIR)
isEmpty(GRDIR) {
  GRDIR = /usr/local/gr
}
TEMPLATE = app
TARGET = qt_meta_test
INCLUDEPATH += .
INCLUDEPATH += $$GRDIR/include
LIBS += -L$$GRDIR/lib -lGR
QMAKE_RPATHDIR += $$GRDIR/lib

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

QT += widgets

# Input
HEADERS += gr_widget.hxx main_window.hxx util.hxx
SOURCES += gr_widget.cxx main.cxx main_window.cxx
