#!/bin/sh
#
py_name=python
if [ "x$PYTHON" != "x" ]
then
  py_name=$PYTHON
fi
PATH=/usr/local/bin:$PATH
py_prefix=`$py_name -c "import sys; print(sys.prefix)"`
py_ver=`$py_prefix/bin/$py_name -V 2>&1 | awk '{print $2}' | awk -F. '{print $1"."$2}' | awk -F+ '{print $1}'`
echo PYTHON_HOME="$py_prefix" PY_VER="$py_ver" `uname`
