GRDIR = S:\gr
QTDIR = S:\Qt\4.8.7
CXXFLAGS = /I$(QTDIR)\include /I$(QTDIR)\include\QtCore /I$(QTDIR)\include\QtGui /I$(GRDIR)
LIBS = /LIBPATH:$(QTDIR)\lib /LIBPATH:$(GRDIR) QtGui4.lib QtCore4.lib libgr.lib qt4gr.lib
OBJ = main.obj main_window.obj


all: main.exe

main.exe: $(OBJ)
	$(CXX) /Fe$@ $(OBJ) /link $(LIBS)

.cpp.obj:
	$(CXX) /c $(CXXFLAGS) $<

clean:
	del main.exe *.obj
