default:
	@cd ..
	@$(MAKE) /f makefile.vc
	@cd .\playground

	COPY ..\libgr3.dll .
	COPY ..\gr3.py .

	DEL *.pyc 2>NUL

clean:
	@cd ..
	@$(MAKE) /f makefile.vc clean
	@cd .\playground

	DEL libgr3.dll

	DEL gr3.py
	DEL *.pyc 2>NUL
	DEL *.png 2>NUL

	DEL *.html 2>NUL

	DEL *.pov 2>NUL

